# Final Project

Your final project is to craft an original work of digital history. That is:

+ You will demonstrate via your project, satisfacory competence and understanding of the five modules in this course
_ie, you conceive, create, document, a work of digital history that_ visualizes _some argument about the past from a the dataset I have given you._

The actual _form_ of the project is up to you: but the key element is that the form you select should follow the function. Some kinds of analyses are better suited to the visual stylings of an infographic; others would be best explicated using a kind of long-form mixture of text and visuals; still others might be best represented via an interactive map or a hand-held locative app.

## Data/Capta

Johanna Drucker exhorts us to remember that 'data' are actually 'capta', that is, they are not 'things given', but rather 'things captured', as it were. (I will use the two terms interchangeably, depending on my mood). We will be working this summer with the digitized editions of the Shawville Equity, from 1883 - 2010. How was this data captured? By what process? To what end? Who paid? _Cui bono_?

## Analysis

You will learn of a number of tools, techniques and approaches to working with capta over the duration of this class. Your project should use at least one of these analytic or exploratory tools in a manner that is suitable given the source data. You will have to think about what the choice of tool does to the kind of story you can tell. Your analysis must be grounded in the appropriate secondary literature for the period/issue. It is **critical** that you use your open notebook and your research narrative to document what you are doing and why. This will enable you to write the accompanying **paradata** document.

You will **share** your final project and all _ancillary files_ by keeping them in a repository in your github space; the final project will be mounted in your own domain. **You will submit your final work to me by sending me the URL via an email with 'Final Project HIST3814o - submitted' as the subject.**

## Visualization

See the tools and techniques in the final two modules of the [workbook](http://workbook.craftingdigitalhistory.ca) for inspiration; make sure your visual styling supports the key themes and ideas your research is exploring.

## Length

In this context, to speak of 'length' makes no sense. Page numbers and word counts do not scholarship make. In years past, students have submitted everything from long form graphically enhanced essays, to interactive maps, to videos, to posters. To know if you're 'done', ask yourself:

*   Have I stated my key questions/provocations well?
*   Are my arguments grounded in appropriate secondary literature?
*   Have I described my methods well enough that someone else could reproduce them?
*   Have I explored the nature of my data/capta and thought through the implications?
*   Does my argument hang together?
*   Do my visuals support/enhance my argument/story?
*   Do I have all my sources (including data & code) cited? Use Harvard author:date style.
*   Have I documented the paradata?

If the answer is 'yes' to all of the above, then you are done.

## Shortcuts

Many digital projects make their code available on Github. You don't have to reinvent the wheel: you merely have to cite it! So google around 'digital history project', and see what people are doing. Keep an eye out for 'how did they do that', a tag that will lead you to videos, walkthroughs, and other useful items. Indeed, the 'how did they do that' is starting to become a recognized academic genre of writing, see for instance the [DHCommons Journal](http://dhcommons.org/journal/issue-1/how-did-they-make-adams-timeline)

## Project Management

Following Appleford, Simon, and Jennifer Guiliano, 'Best Practice Principles Of Designing Your First Project.' DevDH.org, 2013, [http://devdh.org/lectures/design/bestpractice/](http://devdh.org/lectures/design/bestpractice/), the components of a project are the:

1\. the question, problem, or provocation
2\. sources (primary, secondary)
3\. analytical activity
4\. audience
5\. product

Note that 4, audience, comes before 5, product. You **must** think of your reader! Yes, in the first instance, I am the most important reader of your work as I am the one in charge of the gradebook. But that is actually a secondary consideration. Given your data, given your analytic approach, who would most likely be interested in your material? If you were trying to produce an infographic about the debates surrounding the BNA of 1867 for high school classroom use, your use of language, graphics, and colour etc could be very different than if you were just trying to convince **me.**

**Remember: your project work is public.* Design & write accordingly.**

\*unless you have privacy concerns. In which case, you simply have to tell me that you have concerns. I do not need to know what they are. If you wish for your work to be private, we will make it so.
